### ISSUE TITLE
Get all data for water level

### ISSUE THREAD

**Issue by gjahansen2** [GLEON/MilleLacsMystery#7]

**Comment by gjahansen2** [comment]
[ML_water_level.txt](https://github.com/GLEON/MilleLacsMystery/files/872768/ML_water_level.txt)
![mille_lacs_waterlevel_timeseries](https://cloud.githubusercontent.com/assets/19436778/24362602/e627e1f6-12d2-11e7-9fb2-a9d091c1ffab.png)

**Comment by gjahansen2** [comment]
@jread-usgs @lawinslow  Here's the water level data for ML. Makes the recent droughts seem not so bad, in the context of the dust bowl!

**Comment by lawinslow** [comment]
Woot!

**Comment by lawinslow** [comment]
Got the raw data?

**Comment by gjahansen2** [comment]
It's there. ML_water_level.txt. Just above the figure.

**Comment by gjahansen2** [comment]
[ML_water_level.txt](https://github.com/GLEON/MilleLacsMystery/files/873045/ML_water_level.txt)

**Comment by gjahansen2** [comment]
Just in case ^^
Is there a better way for me to share?

**Comment by lawinslow** [comment]
Ah, nope. Here is fine. I'll push it up to the repo.

**Comment by jordansread** [comment]
wow, that's awesome
